[package]
name = "mqtt_listener"
version = "0.1.0"
authors = ["llpghn <patrickberendes@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono="0.4"
termion="*"
paho-mqtt="0.4"